.pr_condition:
  only:
    variables:
      - $RUN_CI_TAG
  except:
    refs:
      - develop
      - master
      - tags

.full_test_condition:
  only:
      variables:
        - $RUN_CI_TAG && $STATUS_CONTEXT == "full"
        - $RUN_CI_TAG && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop")
        - $RUN_CI_TAG && $CI_COMMIT_TAG

.quick_test_condition:
  only:
    variables:
      - $RUN_CI_TAG && $STATUS_CONTEXT == null

.deploy_condition:
  only:
    refs:
      - develop
      - master
      - tags
    variables:
      - $RUN_CI_TAG
  except:
      - schedules
